FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build

WORKDIR /source

COPY . .

RUN dotnet restore "./MyApp.API/MyApp.API.csproj" --disable-parallel

RUN dotnet publish "./MyApp.API/MyApp.API.csproj" -c release -o /app --no-restore


FROM mcr.microsoft.com/dotnet/sdk:6.0-focal

WORKDIR /app

COPY --from=build /app ./

EXPOSE 5000


ENTRYPOINT ["dotnet", "MyApp.API.dll"]